qlib_init:
  provider_uri: "/data/linq/.qlib/qlib_data/cn_data"
  region: cn


model_config: &model_config
  seq_len: 20
  pred_len: 1
  e_layers: 2
  d_layers: 1
  factor: 3
  enc_in: 360
  dec_in: 360
  c_out: 1
  d_model: 64
  d_ff: 32
  top_k: 2
  wavelet_scale: 4
  period_coeff: 0.5
  num_kernels: 6
  dropout: 0.1

task:
  model:
    class: QniverseModel
    module_path: src/model_backbone.py
    kwargs:
      lr: 0.0001
      n_epochs: 1
      max_steps_per_epoch: 1000
      early_stop: 1
      seed: 2024
      logdir: output/wftnet
      model_type: WFTNet
      model_config: *model_config
      freeze_model: False
      model_init_state:
  dataset:
    class: MTSDatasetH
    kwargs:
      seq_len: 20
      horizon: 1
      batch_size: 32
  qlib_dataset:
    class: BENCH_Step
    kwargs:
      market: csi1300_ext
      benchmark: SH000300 
      feat: Alpha360
      label: r1


strategy_config: &strategy_config
  topk: 10
  bad_thresh: -0.05
  hold_thresh: 2
