qlib_init:
  provider_uri: "/content/FinTSB/data/FinTSB_cn"
  region: cn

data_loader_config: &data_loader_config
  class: StaticDataLoader
  module_path: qlib.data.dataset.loader
  kwargs:
    config: /content/FinTSB/data/FinTSB_cn/merged_dataset_FINAL.pkl

    

model_config: &model_config
  seq_len: 20
  pred_len: 1
  e_layers: 2
  factor: 3
  enc_in: 6
  c_out: 1
  d_model: 32  # 32 for LSTM   64 for Adv-LSTM
  d_ff: 16
  n_heads: 2
  dropout: 0.1
  use_attn: False   # False for LSTM
  noise_level: 0.0


task:
  model:
    class: QniverseModel
    module_path: src/model_backbone.py
    kwargs:
      device: "cuda:0"
      lr: 0.0001
      n_epochs: 3
      max_steps_per_epoch: 50
      early_stop: 3
      seed: 2025
      logdir: output/adv_lstm
      model_type: LSTM
      model_config: *model_config
      freeze_model: False
      model_init_state:
  dataset:
    class: UnifiedTSDatasetH
    module_path: src/dataset.py
    kwargs:
      handler:
        class: DataHandler
        module_path: qlib.data.dataset.handler
        kwargs:
          data_loader: *data_loader_config
      segments:
        train: [ "2010-01-04", "2018-08-31" ]
        valid: [ "2018-09-01", "2019-11-30" ]
        test: [ "2019-12-01", "2022-05-12" ]
      seq_len: 20
      horizon: 1
      batch_size: 512


strategy_config: &strategy_config
  topk: 30
  hold_thre: 5
  commission_rate: 0.001